name: Test RPS Scripts

on: [push, pull_request]

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [bash, c, c++]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up base dependencies
      run: |
        sudo apt update
        sudo apt install make -y

    - name: Install C/C++ Compiler
      if: matrix.language == 'c' || matrix.language == 'c++'
      run: |
        sudo apt update
        sudo apt install -y build-essential

    - name: Run RPS Script
      run: |
        [ -d ${{ matrix.language }} ] || exit 0

        pushd ${{ matrix.language }}

        case ${{ matrix.language }} in
          bash)
            bash rps.sh
            ;;
          c)
            make
            ./rps
            ;;
          c++)
            make
            ./rps
            ;;
        esac